name: eslint-check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - name: Eslint project check
        run: make lint
